export const provinces = [
  "Buenos Aires",
  "Catamarca",
  "Chaco",
  "Chubut",
  "Córdoba",
  "Corrientes",
  "Entre Ríos",
  "Formosa",
  "Jujuy",
  "La Pampa",
  "La Rioja",
  "Mendoza",
  "Misiones",
  "Neuquén",
  "Río Negro",
  "Salta",
  "San Juan",
  "San Luis",
  "Santa Cruz",
  "Santa Fe",
  "Santiago del Estero",
  "Tierra del Fuego",
  "Tucumán",
];

export const errorMessages = {
  required: "Este campo es obligatorio",
  min: (num: number) => `Debe tener al menos ${num} caracteres`,
  email: "Ingrese un correo válido",
  minPhone: "Ingrese un número de teléfono válido",
};
